
export const sfxData = {
    "ak 87su" : {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/aks74u_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/aks74u_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/aks74u_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/aks74u_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/aks74u_fire_05.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/aks74u_fire_06.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/aks74u_fire_07.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/aks74u_fire_08.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/762_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/762_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/762_fire_03.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "fireRateDelay": 90 // in milliseconds
    },
    "ak 98" : {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/ak103_fire_01.wav",
                    "modules/vjpmacros/assets/sfx/weapons/firearm/ak103_fire_01.wav",
                    "modules/vjpmacros/assets/sfx/weapons/firearm/ak103_fire_01.wav"],
        "silencedFireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/ak105sd_fire_01.wav",
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "fireRateDelay": 100 // in milliseconds
    },
    "ares executioner": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/m16_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m16_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m16_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m16_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m16_fire_05.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m16_fire_06.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m16_fire_07.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m16_fire_08.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m16_fire_09.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m16_fire_10.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m16_fire_11.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/300_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/300_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/300_fire_03.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/smg_shell_drop_02.wav",
        "fireRateDelay": 80 // in milliseconds
    },
    "ares predator": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/g19comp_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g19comp_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g19comp_fire_03.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/g19xsd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g19xsd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g19xsd_fire_01.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_shell_drop_02.wav",
        "fireRateDelay": 100 // in milliseconds
    },
    "ares vigorous": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/mjolnir_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mjolnir_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mjolnir_fire_03.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/mjolnir_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mjolnir_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mjolnir_fire_03.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "fireRateDelay": 200 // in milliseconds
    },
    "auto-assault 16": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_03.wav"],
        "silencedFireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/m110csass_fire_01.wav",
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/mjolnir_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/shotgun_shell_drop_03.wav",
        "fireRateDelay": 200 // in milliseconds
    },
    "barret model 122": {
        "fireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/mk11_fire_01.wav",
        "silencedFireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/mk11sd_fire_01.wav",
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/mjolnir_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "fireRateDelay": 200 // in milliseconds
    },
    "cavalier arms ebr": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/fnfal_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/fnfal_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/fnfal_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/fnfal_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/fnfal_fire_05.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/fnfal_fire_06.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/fnfal_fire_07.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/fnfal_fire_08.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/asval_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/asval_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/asval_fire_03.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "fireRateDelay": 100 // in milliseconds
    },
    "cavalier deputy": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/1911_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/1911_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/1911_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/1911_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/1911_fire_05.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/1911_fire_06.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/1911_fire_07.wav",],
        "silencedFireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/1911_fire_02.wav",
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/revolver_reload.mp3",
        "ammoCycleSfx": "modules/vjpmacros/assets/sfx/weapons_general/revolver_cycle.ogg",
        "ammoCycleSfxDelay": 700, // in milliseconds
        "fireRateDelay": 900 // in milliseconds
    },
    "cavalier evanator": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/glock_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/glock_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/glock_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/glock_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/glock_fire_05.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/glock_fire_06.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/apc9ksup_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/apc9ksup_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/apc9ksup_fire_01.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/smg_shell_drop_02.wav",
        "fireRateDelay": 75 // in milliseconds
    },
    "colt agent special": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/g22_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g22_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g22_fire_02.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/g22sd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g22sd_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g22sd_fire_03.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/smg_shell_drop_02.wav",
        "fireRateDelay": 100 // in milliseconds
    },
    "colt future frontier": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/nsr_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsr_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsr_fire_03.wav"],
        "silencedFireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/sr3m_fire_01.wav",
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/revolver_reload.mp3",
        "ammoCycleSfx": "modules/vjpmacros/assets/sfx/weapons_general/revolver_cycle.ogg",
        "ammoCycleSfxDelay": 700, // in milliseconds
        "fireRateDelay": 900 // in milliseconds
    },
    "colt new model": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/apc9k_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/apc9k_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/apc9k_fire_03.wav"],
        "silencedFireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/apc9k_fire_01.wav",
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/revolver_reload.mp3",
        "ammoCycleSfx": "modules/vjpmacros/assets/sfx/weapons_general/revolver_cycle.ogg",
        "ammoCycleSfxDelay": 700, // in milliseconds
        "fireRateDelay": 900 // in milliseconds
    },
    "fichetti executive action": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/g19_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g19_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g19_fire_03.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/g19xsd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g19xsd_fire_02.wav"], // only two sounds, the third one is broken
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/smg_shell_drop_02.wav",
        "fireRateDelay": 60 // in milliseconds
    },
    "fichetti military 100": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/mp5a_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp5a_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp5a_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp5a_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp5a_fire_05.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp5a_fire_06.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp5a_fire_07.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/mp5sd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp5sd_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp5sd_fire_03.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/smg_shell_drop_02.wav",
        "fireRateDelay": 60 // in milliseconds
    },
    "fichetti tiffani": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/g22_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g22_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g22_fire_02.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/g22sd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g22sd_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/g22sd_fire_03.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/smg_shell_drop_02.wav",
        "fireRateDelay": 100 // in milliseconds
    },
    "fn mag-5": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/m249spw_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m249spw_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m249spw_fire_03.wav"],
        "silencedFireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/m249sd_fire_01.wav",
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "fireRateDelay": 90 // in milliseconds
    },
    "franchi spas-24": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_03.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_01",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_02",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_03"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/870br_reld.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/shotgun_shell_drop_03.wav",
        "fireRateDelay": 250 // in milliseconds
    },
    "hk xm30": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/hk416_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416_fire_03.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_03.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "fireRateDelay": 80 // in milliseconds
    },
    "hush puppy":  {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/glock_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/glock_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/glock_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/glock_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/glock_fire_05.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/glock_fire_06.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/hushpuppy_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hushpuppy_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hushpuppy_fire_01.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/smg_shell_drop_02.wav",
        "ammoCycleSfx": "modules/vjpmacros/assets/sfx/weapons_general/hush_puppy_reload.ogg",
        "ammoCycleSfxDelay": 500, // in milliseconds
        "fireRateDelay": 100 // in milliseconds
    },
    "ingram smartgun x": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_05.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_05.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/smg_shell_drop_02.wav",
        "fireRateDelay": 50 // in milliseconds
    },
    "krime wave": {
        "fireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/mg40.ogg",
        "silencedFireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/mg40.ogg",
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "fireRateDelay": 57 // in milliseconds
    },
    "marlin 3468ss":{
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/mk17lb_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mk17lb_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mk17lb_fire_03.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/mk18sd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mk18sd_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mk18sd_fire_03.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/bullet_insert.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "ammoCycleSfx": "modules/vjpmacros/assets/sfx/weapons_general/lever_action_repeater.ogg",
        "ammoCycleSfxDelay": 500, // in milliseconds
        "casingDropSfxDelay": 900, // in milliseconds
        "fireRateDelay": 700 // in milliseconds
    },
    "marlin x71": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/nsr_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsr_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsr_fire_03.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/nsrsd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsrsd_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsrsd_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsrsd_fire_04.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/bolt_action_mag_reload.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "ammoCycleSfx": "modules/vjpmacros/assets/sfx/weapons_general/bolt_action.ogg",
        "ammoCycleSfxDelay": 500, // in milliseconds
        "casingDropSfxDelay": 900, // in milliseconds
        "fireRateDelay": 700 // in milliseconds
    },
    "m1 garand": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/urgi_fire_01.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/urgisd_fire_01.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "lastShotSFX": "modules/vjpmacros/assets/sfx/weapons_general/garand_ping.wav",
        "fireRateDelay": 150 // in milliseconds
    },
    "onotari arms equalizer": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/fn57_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/fn57_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/fn57_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/fn57_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/fn57_fire_05.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/apc9ksup_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/apc9ksup_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/apc9ksup_fire_01.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/smg_shell_drop_02.wav",
        "fireRateDelay": 65 // in milliseconds
    },
    "onotari arms jp-k50": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/vulcan_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/vulcan_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/vulcan_fire_03.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/mcxrattlersd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mcxrattlersd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mcxrattlersd_fire_01.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "fireRateDelay": 100 // in milliseconds
    },
    "pjss model 55": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_03.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_01",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_02",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_03"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pjss55_reld.ogg",
        "fireRateDelay": 70 // in milliseconds
    },
    "ppsk-4": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/uzi_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/uzi_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/uzi_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/uzi_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/uzi_fire_05.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/uzi_fire_06.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/apc9ksup_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/apc9ksup_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/apc9ksup_fire_01.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/smg_shell_drop_02.wav",
        "fireRateDelay": 65 // in milliseconds
    },
    "remington 990": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/870br_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/870br_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/870br_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/870br_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/870br_fire_05.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/870br_fire_06.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/870br_fire_07.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_01",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_02",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_03"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/870br_reld.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/shotgun_shell_drop_03.wav",
        "fireRateDelay": 800 // in milliseconds
    },
    "remington roomsweeper": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_03.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_01",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_02",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_03"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/shotgun_shell_drop_03.wav",
        "fireRateDelay": 250 // in milliseconds
    },
    "remington suppressor": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_05.wav",],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/mp7sup_fire_05.wav",],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/smg_shell_drop_02.wav",
        "fireRateDelay": 75 // in milliseconds
    },
    "savalette guardian": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/apc9k_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/apc9k_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/apc9k_fire_03.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/apc9ksup_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/apc9ksup_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/apc9ksup_fire_03.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_shell_drop_02.wav",
        "fireRateDelay": 100 // in milliseconds
    },
    "springfield 2003": {
        "fireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/mk17lb_fire_01.wav",
        "silencedFireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/mk18sd_fire_01.wav",
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/bolt_action_mag_reload.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "ammoCycleSfx": "modules/vjpmacros/assets/sfx/weapons_general/bolt_action.ogg",
        "ammoCycleSfxDelay": 500, // in milliseconds
        "casingDropSfxDelay": 900, // in milliseconds
        "fireRateDelay": 700 // in milliseconds
    },
    "streetline special": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/m9_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m9_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m9_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m9_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m9_fire_05.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m9_fire_06.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m9_fire_07.wav"],
        "silencedFireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/m9sup_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m9sup_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m9sup_fire_03.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/pistol_reldempt.ogg",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/smg_shell_drop_02.wav",
        "fireRateDelay": 100 // in milliseconds
    },
    "ubgl": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/m203_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m203_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m203_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m203_fire_04.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m203_fire_05.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m203_fire_06.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m203_fire_07.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/m203_fire_08.wav",],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/m203_reld.wav",
        "fireRateDelay": 100 // in milliseconds
    },
    "ultamax hmg-2": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/pkm_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/pkm_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/pkm_fire_03.wav"],
        "silencedFireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/pkm_fire_01.wav",
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "fireRateDelay": 90 // in milliseconds
    },
    "ultamax mmg": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/olddshka_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/olddshka_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/olddshka_fire_03.wav"],
        "silencedFireSFX": "modules/vjpmacros/assets/sfx/weapons/firearm/dshka_fire_01.wav",
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "fireRateDelay": 90 // in milliseconds
    },
    "winchester model 2066": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/shotgun_fire_03.wav"],
        "silencedSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_01",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_02",
            "modules/vjpmacros/assets/sfx/weapons/firearm/hk416sd_fire_03"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/870br_reld.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/shotgun_shell_drop_03.wav",
        "ammoCycleSfx": "modules/vjpmacros/assets/sfx/weapons_general/lever_action_repeater.ogg",
        "ammoCycleSfxDelay": 500, // in milliseconds
        "casingDropSfxDelay": 900, // in milliseconds
        "fireRateDelay": 700 // in milliseconds
    },
    "yamaha raiden": {
        "fireSFX": ["modules/vjpmacros/assets/sfx/weapons/firearm/nsrsd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsrsd_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsrsd_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsrsd_fire_04.wav"],
        "silencedFireSFX":["modules/vjpmacros/assets/sfx/weapons/firearm/nsrsd_fire_01.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsrsd_fire_02.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsrsd_fire_03.wav",
            "modules/vjpmacros/assets/sfx/weapons/firearm/nsrsd_fire_04.wav"],
        "emptySFX": "modules/vjpmacros/assets/sfx/weapons_general/gen_empty_02.wav",
        "reloadSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_reldempt.wav",
        "casingDropSFX": "modules/vjpmacros/assets/sfx/weapons_general/rifle_shell_drop_01.wav",
        "fireRateDelay": 80 // in milliseconds
    },
}
